// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrderDBModel = "kitchen_order"

// OrderDBModel mapped from table <kitchen_order>
type OrderDBModel struct {
	ID           int64     `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:自增id" json:"id"`                                                                 // 自增id
	UniqueCode   string    `gorm:"column:unique_code;type:varchar(128);not null;uniqueIndex:uk_order_code,priority:1;comment:订单号[全局唯一]" json:"unique_code"`                                 // 订单号[全局唯一]
	OpenID       string    `gorm:"column:openId;type:varchar(128);not null;uniqueIndex:idx_order_creator,priority:1;comment:创建人id" json:"openId"`                                           // 创建人id
	CreateName   string    `gorm:"column:create_name;type:varchar(128);not null;comment:创建人name" json:"create_name"`                                                                        // 创建人name
	Info         string    `gorm:"column:info;type:varchar(2048);not null;comment:订单内容，暂时不做索引直接怼进去" json:"info"`                                                                            // 订单内容，暂时不做索引直接怼进去
	Status       int32     `gorm:"column:status;type:int(11);not null;default:1;comment:订单状态， 1-新建[提单]  2-已支付" json:"status"`                                                               // 订单状态， 1-新建[提单]  2-已支付
	TargetPeriod string    `gorm:"column:target_period;type:varchar(32);not null;uniqueIndex:idx_order_creator,priority:2;comment:订餐的目标时间，取值只有9个,已校验.明天中午、后天早上、今天晚上等" json:"target_period"` // 订餐的目标时间，取值只有9个,已校验.明天中午、后天早上、今天晚上等
	Extra        string    `gorm:"column:extra;type:varchar(2048);not null;comment:扩展字段" json:"extra"`                                                                                      // 扩展字段
	CreateTime   time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`                                                    // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:最后更新时间" json:"update_time"`                                                  // 最后更新时间
}

// TableName OrderDBModel's table name
func (*OrderDBModel) TableName() string {
	return TableNameOrderDBModel
}
