// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserInfoDBModel = "user_info"

// UserInfoDBModel mapped from table <user_info>
type UserInfoDBModel struct {
	ID           int64     `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:自增id" json:"id"`                      // 自增id
	OpenID       string    `gorm:"column:openId;type:varchar(128);not null;uniqueIndex:uk_open_id,priority:1;comment:微信提供的openId" json:"openId"` // 微信提供的openId
	UserNickName string    `gorm:"column:user_nickName;type:varchar(128);not null;comment:创建人name" json:"user_nickName"`                         // 创建人name
	UserIcon     []byte    `gorm:"column:user_icon;type:mediumblob;comment:暴力存储头像文件" json:"user_icon"`                                           // 暴力存储头像文件
	Status       int32     `gorm:"column:status;type:int(11);not null;default:1;comment:1-正常状态  2-删号" json:"status"`                             // 1-正常状态  2-删号
	CreateTime   time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`         // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;type:timestamp;default:CURRENT_TIMESTAMP;comment:最后更新时间" json:"update_time"`                // 最后更新时间
	UserIconURL  string    `gorm:"column:user_icon_url;type:varchar(512);not null" json:"user_icon_url"`
}

// TableName UserInfoDBModel's table name
func (*UserInfoDBModel) TableName() string {
	return TableNameUserInfoDBModel
}
